### ISSUE TITLE
armhf not supported?

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/rocketchat_ynh#1]
Hi @realitygaps,

so installing mongodb doesn't seem to work on armhf (e.g. LIME2), right?

And why does this refer to wheezy and not to jessie?

https://github.com/realitygaps/rocketchat_ynh/blob/master/scripts/install#L20

Thanks for the efforts!

**Comment by realitygaps** [comment]
its still not really a finished package, so we've focused on x86 testing on our servers so far - but will try it on my lime (thought maybe it would be too heavy, and also takes a long time to install whilst testing).

The wheezy thing is the way mongo seems to have (mis)named their repositories, I also found it strange. Hopefully we get some time to test the package this month on the lime2.
