### ISSUE TITLE
Add CI at ci-apps.yunohost.org + github webhook

### ISSUE THREAD

**Issue by dicer** [YunoHost-Apps/rocketchat_ynh#10]
Add Travis CI auto-builds and check to this repo

**Comment by selamanse** [comment]
I think its better to use the ci job at https://ci-apps.yunohost.org/jenkins/ ...let's ask @frju365 he can integrate the job and create a github webhool.

**Comment by frju365** [comment]
A hook will be created and a test will be made Friday.
I can add your app on the non-official CI too if you need a test quickly.

**Comment by selamanse** [comment]
@dicer I have now also activated basic package lint check via travisci

**Comment by selamanse** [comment]
I added the webhook to https://ci-apps.yunohost.org/jenkins/github-webhook/ in this repo and discovered that the build is running every 10 days (scheduled).
