### ISSUE TITLE
URL path when installing

### ISSUE THREAD

**Issue by sthaydn** [YunoHost-Apps/rocketchat_ynh#129]
Hi there,

great you have sorted out the install issues.

When installing now, I always get rocket.domain.tld/rocketchat (when choosing GUI install I have to enter a path, not when using Terminal, but there it does the path even when not entering one), but I only want to have rocket.domain.tld. When changing it via GUI, I am not able to connect then.

What could I do?

Regards,

Stefan

**Comment by ericgaspar** [comment]
I am installing Rocket.Chat on sub-path -> `domain.tld/rocketchat` and in a sub-domain `rocket.domain.tld` without issue... 

The change_url script as a bug. The systemd config should be regenerated as we need to change domain and path variables: `Environment=ROOT_URL=https://__DOMAIN____PATH__`

**Comment by ericgaspar** [comment]
Closing with #128
