### ISSUE TITLE
Rocket.chat server crash when android app logs in

### ISSUE THREAD

**Issue by KamuiX** [YunoHost-Apps/rocketchat_ynh#135]
My YunoHost server
Hardware: An old rig with an Intel(R) Core™2 Duo CPU E8400 @ 3.00GHz, 8GB of RAM and 3x500GB in RAID 5
YunoHost version: 4.3.6.3 (stable)
I have access to my server : SSH and Web

Description of my issue

After succesufully installed the yunohost app (test tree) because I am using an old non AVX processor https://github.com/YunoHost-Apps/rocketchat_ynh/issues/132#issuecomment-1181683056 
I came up with a new problem and that is connect through Android client.

Whenever a user tries to connect from Android APP the below error appears on server and server TOTALY crash!

Jul 20 23:03:07 rocketchat[11286]: +----------------------------------------------------------+
Jul 20 23:03:07 rocketchat[11286]: |                      SERVER RUNNING                      |
Jul 20 23:03:07 rocketchat[11286]: +----------------------------------------------------------+
Jul 20 23:03:07 rocketchat[11286]: |                                                          |
Jul 20 23:03:07 rocketchat[11286]: |  Rocket.Chat Version: 4.8.1                              |
Jul 20 23:03:07 rocketchat[11286]: |       NodeJS Version: 14.20.0 - x64                      |
Jul 20 23:03:07 rocketchat[11286]: |      MongoDB Version: 4.4.15                             |
Jul 20 23:03:07 rocketchat[11286]: |       MongoDB Engine: wiredTiger                         |
Jul 20 23:03:07 rocketchat[11286]: |             Platform: linux                              |
Jul 20 23:03:07 rocketchat[11286]: |         Process Port: 3001                               |
Jul 20 23:03:07 rocketchat[11286]: |             Site URL: removed for security reasons  |
Jul 20 23:03:07 rocketchat[11286]: |     ReplicaSet OpLog: Enabled                            |
Jul 20 23:03:07 rocketchat[11286]: |          Commit Hash: 0b106e3645                         |
Jul 20 23:03:07 rocketchat[11286]: |        Commit Branch: HEAD                               |
Jul 20 23:03:07 rocketchat[11286]: |                                                          |
Jul 20 23:03:07 rocketchat[11286]: +----------------------------------------------------------+
Jul 20 23:03:30 rocketchat[11286]: {"level":40,"time":"2022-07-20T20:03:30.305Z","pid":11286,"hostname":"removed","name":"API","msg":"attribute query is deprecated"}
Jul 20 23:03:30 systemd[1]: rocketchat.service: Main process exited, code=killed, status=4/ILL
Jul 20 23:03:30 systemd[1]: rocketchat.service: Failed with result 'signal'.

**Comment by ericgaspar** [comment]
your issue seems to be close to this one...
https://forums.rocket.chat/t/first-install-rocket-chat-crashes-after-a-few-minutes/13307

**Comment by KamuiX** [comment]
Although there are some big differences
1) Mine is event driven (APP login) and not time driven (after few minutes)
2) I am on Yunohost (debian) not Centos

but the truth is that they are talking about "old CPUs" and that makes me wonder again.

--EDIT--

Oups just read "Update: I have isolated this when I open the mobile app, it crashes the service on the server every time."

--EDIT 2--

Once again it seems AVX is hunting me. This time a node.js package called "sharp" or "vips" seems to have the issue here. I am not familiar with node.js so if someone can guide me how to downgrade these packages to a non-AVX version just for testing purposes.

**Comment by ericgaspar** [comment]
Closing this. Please reopen if needed
