### ISSUE TITLE
iOS App doesn't connect

### ISSUE THREAD

**Issue by sthaydn** [YunoHost-Apps/rocketchat_ynh#155]
Hi there,

RocketChat is working fine with Android and Linux on my yunohost with all on latest version. Also the macOS works fine, but no chance to get it working on iOS.

After inserting my credentials and clicking on connect, nothing happens.

Is this something known, or is this a "special feature" on my yunohost install?

Regards,

Stefam

**Comment by ericgaspar** [comment]
@sthaydn  Most of the time, the problem occurs when rocket.Chat is installed as private app during install. You can change the permission to public in the webadmin > Applications > Rocket.Chat  > Manage groups and permissions

**Comment by sthaydn** [comment]
It is set to all_users and visitors. Visitors is public, I guess?

**Comment by ericgaspar** [comment]
FYI, I have Rocket.Chat working fine on iOS...

**Comment by sthaydn** [comment]
Ok, thanks for that. So it seems there is an issue on my side. Where are the logfiles from RocketChat?

**Comment by ericgaspar** [comment]
> Ok, thanks for that. So it seems there is an issue on my side. Where are the logfiles from RocketChat?

Webadmin -> Services ->  rocketchat

**Comment by sthaydn** [comment]
Ok, there are no entries with logging in. Do you have another idea what I could investigate?

**Comment by getzze** [comment]
Hi, I also have the same problem, it works everywhere but iOS.
I followed [this](https://forums.rocket.chat/t/the-ios-version-cannot-be-logged-in/13475), but nothing works.
Still have to try [this](https://forums.rocket.chat/t/error-you-must-be-logged-in-to-do-this-with-status-code-401unauthorized/9804/3).

**Comment by getzze** [comment]
I managed to make it work!
I had previously set the [security setting](https://yunohost.org/en/security#change-cipher-compatibili) for nginx to "modern", so it was using only TLSv1.3, but I guess it doesn't work on old iphones.
Setting it to intermediate makes it work:
```
sudo yunohost settings set security.nginx.compatibility -v intermediate
```

What is strange is that I tried adding this line to `/etc/nginx/conf.d/rocketchat.my.subdomain.conf`:
`ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # don’t use SSLv3 ref: POODLE`
But it was not allowing tlsv1.2 on this subdomain...

**Comment by sthaydn** [comment]
After reading your comment it hit me really hard. :-D I did exactly the same a long time ago, haven't remembered it until now. Thank you very much! It also works for me now.

But, you are right, I would also have "modern" set as default and only have changed that where it is necessary.

**Comment by mrPsycho** [comment]
i also just installed it and wondered why ios is broken… 
but yeah, lowered security level and it started to work
