### ISSUE TITLE
Unable to login as admin

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/rocketchat_ynh#185]
### Describe the bug

- Admin user cannot login
- Random people can register as admins.
- Unable to view `general` channel.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.3
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master - 6.2.9
- If upgrading, current package version: fresh install

### Steps to reproduce

 1. Install app, select admin user and password
 2. On main page enter name of the selected user and selected password
 
 3. Create different user
 4. User is admin for some reason
 5. Go to `general` channel

### Expected behavior
 pt 2. Successful login - actual 'no such use or wrong password'

 pt 4. Why can a random person register as admin, especially given default access to app is 'visitors'

 pt 5. this throws me back to YunoHost portal, network inspector shows failed xhr prior to that.

### Logs

No meaningful logs anywhere, even when observing NodeJS output.

**Comment by ericgaspar** [comment]
should be fixed
