### ISSUE TITLE
Uninstall leaves 'husk' mongod service.

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/rocketchat_ynh#187]
### Describe the bug

After uninstalling Rocket.Chat, which is the only app that uses MongoDB, broken 'mongod' service is present in WebUI.

Service is added in [`ynh_install_mongo`](https://github.com/YunoHost-Apps/rocketchat_ynh/blob/97433acad7d8bb7c5e49ef7ef9f9bde3d3972e66/scripts/_common.sh#L353) and would be deprovisioned in [`ynh_remove_mongo`](https://github.com/YunoHost-Apps/rocketchat_ynh/blob/97433acad7d8bb7c5e49ef7ef9f9bde3d3972e66/scripts/_common.sh#L373) if it wasn't for the fact that with packaging v2 this script runs before apt is deprovisioned.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.3
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 6.2.9~ynh1

### Steps to reproduce

1. Install app
2. Remove app

### Expected behavior

All provisioned services removed.

### Logs

https://paste.yunohost.org/raw/lihuliporo

**Comment by stilobique** [comment]
True, I have this issue since uninstall this app.

**Comment by orhtej2** [comment]
You can always `sudo yunohost service remove mongod`.

**Comment by ericgaspar** [comment]
should be fixed
