### ISSUE TITLE
Rocketchat throwing database error and kicks me back to Yunohost user dashboard whenever I try to select a channel.

### ISSUE THREAD

**Issue by KnightNine** [YunoHost-Apps/rocketchat_ynh#188]
### Describe the bug

Rocketchat was loading infinitely when I opened it, so I thought to update my rocketchat to 6.3.1~ynh1 and yunohost instance and now it lets me login and manage settings, but selecting a channel kicks me back to my yunohost dashboard.

Rocketchat is also giving me this broken notification `MongoDB Deprecated, MongoDB version %s is deprecated, please upgrade your installation.` where it doesn’t show the version.

### Context

Hardware: Old laptop
YunoHost version: 11.2.3 (stable)
I have access to my server : yes
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

### Steps to reproduce

I am unsure of how to reproduce it. This just started being an issue after updating. And I am unsure about how or when the infinite loading set in, it was working fine before.

### Expected behavior

I should be able to access my channels.

### Logs

Yunohost did not throw any errors but here's the diagnosis:
https://paste.yunohost.org/raw/apecuyiwem

and the update rocketchat log:
https://paste.yunohost.org/raw/ajirehijej

here's the console after logging into rocketchat:
![rocketchat](https://github.com/YunoHost-Apps/rocketchat_ynh/assets/34152090/5168cab0-5094-4635-b8f9-28c830156552)

**Comment by KnightNine** [comment]
Is there anything I can do to fix this? Will uninstalling and reinstalling the rocketchat app wipe all my rocketchat data?

**Comment by bugness-chl** [comment]
Rocket.Chat v.6.3.1~ynh1 on Yunohost 11.2.3 here.

I had the same problem of being redirected to the dashboard when clicking some links (channels, options, etc.) and those links don't actually contain the path of Rocket.Chat. Worse, it seems that installing Rocket.Chat in a path/subdir/subfolder is not supported anymore : https://github.com/RocketChat/Rocket.Chat/issues/29331#issuecomment-1559084974

I managed to workaround by dedicating a subdomain to RocketChat :
* at `/yunohost/admin/#/domains` : create a subdomain and generate the Let's Encrypt certificate for it,
* at `/yunohost/admin/#/apps/rocketchat/operations` : configure the access URL of RocketChat to use it (without path),
* and, not sure if it's a good idea, but I also had to modify `/etc/systemd/system/rocketchat.service` and `/etc/yunohost/apps/rocketchat/settings.yml` like below, before launching a `systemctl daemon-reload && systemctl restart rocketchat.service` :
```
# /etc/systemd/system/rocketchat.service
# remove any double '/' at the end of this URL
Environment=ROOT_URL=https://rocketchat.example.com/

# /etc/yunohost/apps/rocketchat/settings.yml
path: ''
```

Testing in progress, fingers crossed...

**Comment by KnightNine** [comment]
@bugness-chl 
Noticed that the links were directing me to `mydomain.noho.st/channel/Programming` rather than `mydomain.noho.st/rocketchat/channel/Programming`  so I created a dedicated subdomain with no additional path and now it works!

I'm still getting that broken mongoDB alert for some reason but at least I can now use the app.

Thanks.

**Comment by ericgaspar** [comment]
I removed  installation in subfolder from the install script in a rather harsh way, sorry.
You can also use change_url in the app webadmin to transfer Rocket.Chat from a subfolder to dedicated domain.
