### ISSUE TITLE
Bad use of checkurl ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/rocketchat_ynh#27]
Hello,

I don't have time to write a full issue description, but please have a look at : https://forum.yunohost.org/t/installation-of-2-community-apps-fails/3668/10

**Comment by dicer** [comment]
True, we use it on its own subdomain so we never noticed. @selamanse has a test server where he could try this out.

Are there any expected side effects from changing the line?
```sudo yunohost app checkurl $domain$path -a $app```

https://github.com/YunoHost-Apps/rocketchat_ynh/blob/d4a4ebe976dc1ca8568b9a8bc4367f5f4017a4e7/scripts/install#L38

**Comment by alexAubin** [comment]
Checkurl does 2 things : 
- It checks that the URL is available (i.e. that no app already booked a parent URL of this app (e.g. if an app is installed on `/wordpress`, you can't book `/` and vice-versa)
- It not available, it triggers an error (return code != 0)
- If it's available, it books/registers it

So your current code ($domain alone) actually booked the full domain for rocketchat even if you installed it on a subdomain :s 

Anyway, we changed this recently (the whole checkurl thing) because it was causing some issue that there were actually 2 separate things in this command (check and actual booking/registering).

In fact nowadays you should use the helper `ynh_webpath_register` [here](https://github.com/YunoHost/yunohost/blob/unstable/data/helpers.d/network#L54-L61)

So in your case : 

```
ynh_webpath_register $app $domain $path
```

If you really want to be sure, you can use `ynh_webpath_available` to assert that the path really is available (and cancel the install if it's not), but it should normally be checked by the yunohost core before launching the actual install.
