### ISSUE TITLE
Checksum error 

### ISSUE THREAD

**Issue by antaeusdk** [YunoHost-Apps/rocketchat_ynh#33]
Steps where I can reproduce the error (from CLI)
1. Clone the repo via git
2. Edit the "install" script file to contain $path in the checkurl refference
3. Run yunohost app install ./rocketchat_ynh/ --debug

`73810 INFO ++ sha256sum /var/lib/rocketchat/rocket.chat-0.58.4.gtar`
`73810 WARNING The sha256sum does not match the configured one`
`73843 WARNING !!`
`73846   rocketchat's script encountered an error. Its execution was cancelled.`
`73852 WARNING !!`

![2017-11-02 09_01_46-srv - teamviewer](https://user-images.githubusercontent.com/2125190/32315485-900ba672-bfac-11e7-8020-57877f365bf5.png)

I have been round and forth first with a longer thread with Aleks: https://forum.yunohost.org/t/installation-of-2-community-apps-fails/3668/
Then in the chat, where it ended out with being a checksum error in the install.

**Comment by dicer** [comment]
Should be fixed by commit b4550cc

**Comment by selamanse** [comment]
@antaeusdk the reason for this is documented here #30 (short: rocket.chat has changed download locations resulting in a 404 page being downloaded instead of bundled app).

I will close this for now. Please feel free to reopen if the problem persists.
