### ISSUE TITLE
Update installs latest version, not the one we want to

### ISSUE THREAD

**Issue by dicer** [YunoHost-Apps/rocketchat_ynh#34]
We should use the configured version in the update script. It's kind of dangerous to just download the latest version for several reasons:

  -  no shasum check here
  -  no idea if dependencies are met
  -  untested release by us
  -  etc.

That said I think we also need to think about copying changes we make to the install script in here. Like installing new nodejs versions. If you just upgrade you never get these new dependencies.

**Comment by selamanse** [comment]
closing because this was already implemented.
