### ISSUE TITLE
Introduce package to yunohost forum 

### ISSUE THREAD

**Issue by selamanse** [YunoHost-Apps/rocketchat_ynh#4]
I'd like to contribute #3 and also support this package to be registered in the ynh forums.

**Comment by realitygaps** [comment]
Great! I haven't had time to work on making this package work properly for a while, I merged your changes now.

**Comment by selamanse** [comment]
I'd really like to improve further and list this package as an unofficial app for more testing via community. Can you add me as a collaborator here plz?

**Comment by selamanse** [comment]
I've created some awareness [here](https://forum.yunohost.org/t/rocketchat-for-ynh-package/3189 ), hope you don't mind?

**Comment by selamanse** [comment]
done. also see discussion here...#8
