### ISSUE TITLE
Release referenced in community.json fails to install 

### ISSUE THREAD

**Issue by arthurzenika** [YunoHost-Apps/rocketchat_ynh#40]
The latest release 0.58.3-ynh1 referenced in  https://github.com/YunoHost/apps/blob/master/community.json#L969 seems to fail to install because of `yunohost app checkurl` which has been fixed https://github.com/YunoHost-Apps/rocketchat_ynh/commit/9c25bc0ca3ad5fc34d3cbf9c9abd8566aa16eb60

It would be nice to release a new version and update the community.json file. We've successfully installed rocketchat_ynh by using the github url in yunohost

**Comment by selamanse** [comment]
thanks for the hint 👍  I have now released [0.58.4-ynh1](https://github.com/YunoHost-Apps/rocketchat_ynh/releases/tag/0.58.4-ynh1) and opened the requested pr.
