### ISSUE TITLE
Latest mobile client needs newer server version

### ISSUE THREAD

**Issue by dicer** [YunoHost-Apps/rocketchat_ynh#44]
Latest mobile clients complain about an too old server version. 0.62.0 or 0.63.0 seem to be the minimum versions depending on which source you look at.

![screenshot_20180419-090847](https://user-images.githubusercontent.com/219524/39088782-a7baef70-45b8-11e8-88eb-377775dcd380.png)
![screenshot_20180419-090631](https://user-images.githubusercontent.com/219524/39088784-b384ea22-45b8-11e8-9145-27aaa1da859f.png)

Are there any new dependencies that would block us from releasing a newer version?

**Comment by selamanse** [comment]
I have merged PR  #46 which should resolve this issue.

**Comment by selamanse** [comment]
I have released [0.64.0-ynh1](https://github.com/YunoHost-Apps/rocketchat_ynh/releases/tag/0.64.0-ynh1 )

**Comment by selamanse** [comment]
@dicer I have opened PR #61 can you please have a look? Also closing this because I think its not an issue anymore. feel free to reopen.
