### ISSUE TITLE
User can't connect when have more than one email

### ISSUE THREAD

**Issue by plopoyop** [YunoHost-Apps/rocketchat_ynh#45]
I create the issue to follow the upstream bug :  https://github.com/RocketChat/Rocket.Chat/issues/10247

**Comment by selamanse** [comment]
@plopoyop this is an rocket chat issue and not directly addressable within this package. If you feel otherwise please reopen and let us discuss what we can do to solve the issue or how we can enhance the application from installer view (or yunohost view).

**Comment by plopoyop** [comment]
It was just a way to track an upstream bug, but whatever
