### ISSUE TITLE
404 on https://download.rocket.chat/build/rocket.chat-0.64.1.tgz

### ISSUE THREAD

**Issue by adimascio** [YunoHost-Apps/rocketchat_ynh#49]
Hi,

I'm trying to install the latest version of rocket chat (0.64.1) within yunohost but the download URL generated (i.e. `https://download.rocket.chat/build/rocket.chat-0.64.1.tgz`) seems invalid. Does anyone know if it's temporary or if the URL scheme has recently changed?

**Comment by selamanse** [comment]
Seems it has changed...(again)... I will try to find out how and why.

**Comment by selamanse** [comment]
ok I found a hint here...

RocketChat/Rocket.Chat#8998

seems only the bucket url from their ci build is valid at the moment (also saw this in the [circle-ci script](https://github.com/RocketChat/Rocket.Chat/blob/c4c0f67c911a663aa9ffe8fb67bf6890b70cb7b8/.circleci/config.yml#L245)):

https://s3.amazonaws.com/download.rocket.chat/build/rocket.chat-0.64.1.tgz

I will fix this asap.

**Comment by selamanse** [comment]
Integration tests are running: 
https://travis-ci.org/selamanse/rocketchat_ynh/builds/380755337
