### ISSUE TITLE
Can't log in after installation

### ISSUE THREAD

**Issue by antaeusdk** [YunoHost-Apps/rocketchat_ynh#56]
When installing Rocket.Chat on a Yunohost 2.7* instance, after finished installation, log in will not be possible.
Leaving the installation window open works.
If opening in another browser, the correct credentials will not be accepted.

**Comment by selamanse** [comment]
Hi @antaeusdk. can you please use the updated package and test this again? Also a bit more info about your system and installation would be helpful (ynh version and rocketchat_ynh commit id) so I can try to reproduce.

**Comment by selamanse** [comment]
@antaeusdk closing this. please reopen if necessary.
