### ISSUE TITLE
Login in to Mobile app throwing Errors

### ISSUE THREAD

**Issue by dixon-hill** [YunoHost-Apps/rocketchat_ynh#57]
I have tried to login to our chat interface through the mobile app, and ever since the update I can only get my teams internal chat working, not the public chat.

So I logged out completely and entered the URL of the public chat for the server name and when I enter my name and password I get this error:
![img_4179](https://user-images.githubusercontent.com/35572945/44353497-03a6a700-a45c-11e8-8ee9-071715f1af32.PNG)

Any ideas?

**Comment by selamanse** [comment]
@dixon-hill can you please give some insight about your yunohost server system, mobile app name and version and ynh version? Otherwise this won't be easy to reproduce.

**Comment by selamanse** [comment]
@dixon-hill closing this for now - if your problem persists: please provide more detailed info & reopen this issue.
