### ISSUE TITLE
Your app is broken

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/rocketchat_ynh#60]
Hello

Your app is failing on our CI
https://ci-apps.yunohost.org/ci/job/434

Please try to fix this app before Sunday 21th, otherwise it will be set at notworking.
If you need help, don't hesitate to ask on our chat rooms,
- IRC: #yunohost-apps on irc.freenode.net
- Matrix: #freenode_#yunohost-apps:matrix.org
- XMPP: apps@conference.yunohost.org

**Comment by selamanse** [comment]
@maniackcrudelis ok I am on it :) thanks for notice.

**Comment by selamanse** [comment]
It’s working now:

https://ci-apps.yunohost.org/ci/job/679

**Comment by selamanse** [comment]
@maniackcrudelis Unfortunately the ynh ci-stretch server sends mails with failed but is not accessible for me. Is this in any way different from ci-apps server where it works? Help appreciated :)
