### ISSUE TITLE
Update to 0.73.2 failed

### ISSUE THREAD

**Issue by peatsn** [YunoHost-Apps/rocketchat_ynh#69]
**Logfile Output**
`
2019-02-02 20:14:26,887: WARNING - Warning: apt-key output should not be parsed (stdout is not a terminal)
2019-02-02 20:14:31,919: WARNING - tar (child): /var/lib/rocketchat/rocket.chat-0.73.2.gtar: Cannot open: No such file or directory
2019-02-02 20:14:31,922: WARNING - tar (child): Error is not recoverable: exiting now
2019-02-02 20:14:31,923: WARNING - tar: Child returned status 2
2019-02-02 20:14:31,924: WARNING - tar: Error is not recoverable: exiting now
2019-02-02 20:14:31,924: WARNING - !!
2019-02-02 20:14:31,925: WARNING -   rocketchat's script has encountered an error. Its execution was cancelled.
2019-02-02 20:14:31,925: WARNING - !!
2019-02-02 20:14:31,925: WARNING - 
2019-02-02 20:14:32,036: ERROR - Unable to upgrade rocketchat
`

I think this part from upgrade script doesn't work

 echo "Downloading rocket.chat-$ROCKETCHAT_VERSION.gtar from ${ROCKETCHAT_DOWNLOAD_URI}."
sudo curl -s -L -o $final_path/rocket.chat-$ROCKETCHAT_VERSION.gtar "${ROCKETCHAT_DOWNLOAD_URI}"
SHA_DOWNLOAD=$(sha256sum $final_path/rocket.chat-$ROCKETCHAT_VERSION.gtar | grep -o "^[a-f0-9]*")
if [[ ! "$SHA_DOWNLOAD" == "$ROCKETCHAT_SHASUM" ]]; then
  ynh_die "The sha256sum does not match the configured one"
fi

sudo systemctl stop rocketchat

**sudo rm -rf $final_path**
**sudo mkdir -p $final_path**

installnode

sudo tar -xzf $final_path/rocket.chat-$ROCKETCHAT_VERSION.gtar -C $final_path --strip-components=1 bundle
sudo rm $final_path/rocket.chat-$ROCKETCHAT_VERSION.gtar

**Comment by selamanse** [comment]
@peatsn thanks for submitting your issue. can you please rerun setup on cli with `yunohost app upgrade rocketchat_ynh --debug`. Also please add which environment this is run on OS and architecture wise. Thank you.

**Comment by peatsn** [comment]
Running the update via webinterface shows the error above.

**yunohost app upgrade rocketchat_ynh --debug**
180  DEBUG loading actions map namespace 'yunohost'
195  DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
195  DEBUG initializing base actions map parser for cli
196  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
270  DEBUG initialize authenticator 'ldap-anonymous' with: uri='ldap://localhost:389', base_dn='dc=yunohost,dc=org', user_rdn='None'
278  DEBUG lock has been acquired
315  DEBUG loading python module yunohost.app took 0.037s
316  INFO processing action [11188.1]: yunohost.app.upgrade with args={'url': None, 'app': ['rocketchat_ynh'], 'auth': <moulinette.authenticators.ldap.Authenticator object at 0x7fc5bae87850>, 'file': None}
459  INFO Upgrading apps rocketchat_ynh
459  INFO Upgrading app rocketchat_ynh…
459  DEBUG action [11188.1] executed in 0.143s
459  DEBUG lock has been released
459  ERROR rocketchat_ynh is not installed

**yunohost app upgrade https://github.com/YunoHost-Apps/rocketchat_ynh --debug**
191  DEBUG loading actions map namespace 'yunohost'
213  DEBUG extra parameter classes loaded: ['comment', 'ask', 'password', 'required', 'pattern']
214  DEBUG initializing base actions map parser for cli
215  DEBUG registering new callback action 'yunohost.utils.packages.ynh_packages_version' to ['-v', '--version']
307  DEBUG initialize authenticator 'ldap-anonymous' with: uri='ldap://localhost:389', base_dn='dc=yunohost,dc=org', user_rdn='None'
315  DEBUG lock has been acquired
347  DEBUG loading python module yunohost.app took 0.031s
347  INFO processing action [11201.1]: yunohost.app.upgrade with args={'url': None, 'app': ['https://github.com/YunoHost-Apps/rocketchat_ynh'], 'auth': <moulinette.authenticators.ldap.Authenticator object at 0x7f44266f0850>, 'file': None}
500  INFO Upgrading apps https://github.com/YunoHost-Apps/rocketchat_ynh
500  INFO Upgrading app https://github.com/YunoHost-Apps/rocketchat_ynh…
500  DEBUG action [11201.1] executed in 0.153s
500  DEBUG lock has been released
501  ERROR https://github.com/YunoHost-Apps/rocketchat_ynh is not installed

runs on 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Comment by selamanse** [comment]
@peatsn thank you for the logs.
I am not sure if you were upgrading because it states in the logs that `501 ERROR https://github.com/YunoHost-Apps/rocketchat_ynh is not installed`

So you might have to install (again?) via:
`yunohost app install https://github.com/YunoHost-Apps/rocketchat_ynh --debug`

I am currently also trying to setup a test system with your specs and reproduce the problem.

**Comment by peatsn** [comment]
i definitly ran an update on my production rocketchat via the webinterface. The update procedure deletes all under /var/lib/rocketchat

**Comment by selamanse** [comment]
@peatsn that is correct - it is the program directory for rocketchat. Note: it doesnt remove the actual data which resides in mongodb.

Since I am guessing you cannot backup via ui: Before trying anything else I would recommend backing up your data by manually running: `sudo mongodump -o "~/rocketchat.dump"`

After this can you please give it a try by reinstalling via  `yunohost app install https://github.com/YunoHost-Apps/rocketchat_ynh --debug` ?

**Comment by selamanse** [comment]
@peatsn I could reproduce the problem and it is the part you mentioned in the beginning of this thread. The part of downloading the newer version was moved to the part before the app dir was removed. Unfortunately the app dir is the destination for this download - so the downloaded file is being removed, causing the upgrade to fail.

I have the fix coming - and this time I try to double check this by running my integration tests first and also pushing into testing before going to master. Will keep you informed.

**Comment by selamanse** [comment]
@peatsn just a little feedback here:

I have verified the fix in my integration-test branch (fork) and created a testing branch here which is still due for building on yunohost ci servers..

unfortunately it takes some time (days).

You can either wait and see the status here:
https://ci-apps-unstable.yunohost.org/ci/apps/rocketchat/

Or you can lookup test results for testing lane here:
https://dash.yunohost.org/appci/app/rocketchat

I will merge the #71 as soon as the testing branch is stable.

**Comment by arthurzenika** [comment]
I think I hit something similar to this. Any news on the fix in testing getting into master ?
