### ISSUE TITLE
Local videos 

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/rocketchat_ynh#72]
Hey guys I got a problem after upgrade everything was fine but this morning something wrong happen direct links is working fine but when trying to play like https://hostyour.tv/videos/watch/4aceb60c-c0cc-4d40-8ae7-75f57ccfe033 this video nothing happens seed is gone...

**Comment by selamanse** [comment]
Hello @filmaidykai, thank you for submitting an issue.

Can you please add information on your installation? Which OS Version are you running? Which Yunohost Version?

Also - if this an application problem with rocket chat - I would suggest opening an issue here:
https://github.com/RocketChat/Rocket.Chat/issues
