### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/rocketchat_ynh#73]
Your app is currently failing all tests on our CI.
https://ci-apps.yunohost.org/ci/job/2537

Unless the app is fixed before next Saturday, 13th, this app will be set at notworking.

**Comment by dosch** [comment]
@selamanse any chance rocket chat might return to YNH?

**Comment by selamanse** [comment]
@dosch Hacktoberfest is near. I cannot make any promises about the return but I will try to look into what can be done. :)

**Comment by ericgaspar** [comment]
I have worked on RocketChat on testing branch. I am able to install it but CI tests are failing
