### ISSUE TITLE
Change ownership of repo to Organization: YunoHost-Apps

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/rocketchat_ynh#8]
Bonjour, 
Il serait bien, pour une meilleure gestion des applications et une meilleure gestion des contributions, que toutes les apps rejoignent l'organisation **Yunohost-Apps**.
Merci,
frju365
_____
Hello,
To manage in a better way the contributions and the Apps, we invite you to change the ownership of your app  to **Yunohost-Apps** Organization. 
Thanks,
frju365

**Comment by selamanse** [comment]
@realitygaps this is to gain more support from the main community. All your repo rights remain as they are. Can you please transfer the repo to the above mentioned Org? I already have created a team called rocketchat.

**Comment by selamanse** [comment]
@realitygaps don't want to stress you out but I'd like to push this a little farther so we can implement updates quicker and more easily by adding people. If you transfer this to the Organization it would be nice, because we can work as a collaborative team...Also we would be added to the automated build pipeline @ http://ci-apps.yunohost.org/.

**Comment by frju365** [comment]
Euh, is there a problem in changing the owner of the repos ?

**Comment by selamanse** [comment]
@frju365 no problem - I just put in a reminder 😃

**Comment by realitygaps** [comment]
" You don’t have the permission to create repositories on YunoHost-Apps "

Im currently on vacation, hence the delayed replies

**Comment by selamanse** [comment]
@realitygaps no need to create a new repo. 
You can use the settings of this repo to transfer as described [here](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) in section "Transferring a repository to another user account or to an organization". 

While transferring you will be prompted for a team. please use the team "rocketchat" that I already created

**Comment by realitygaps** [comment]
That was what i tried, will attempt again from a non-mobile device when i get a chance

**Comment by frju365** [comment]
sorry... It's my fault. I believed that I invited you to the Yunohost-Apps Organization. Sorry ! 
Can you retry now after having accepted the invitation ? I think it will work now. (indeed, you can't transfer a repos to an orga you don't belong too)

**Comment by realitygaps** [comment]
hmm i still dont see an organisation invite

**Comment by frju365** [comment]
I think it was send by email. Or you can accept it on by enter this URL : https://github.com/YunoHost-Apps.

**Comment by realitygaps** [comment]
OK, should be transferred now

**Comment by frju365** [comment]
Nice ! Thanks !
