### ISSUE TITLE
Change url

### ISSUE THREAD

**Issue by getzze** [YunoHost-Apps/rocketchat_ynh#80]
Hi,
I installed Rocket.chat with the `testing` branch (https://github.com/YunoHost-Apps/rocketchat_ynh/commit/6e94ffa6b2fae0ccd6230fbe6296310a2fb9dc96).
I just had to comment line 147 `mongo --eval "printjson(rs.initiate())"` in `scripts/install`, but I managed to install it.

I also had another problem (introduced with the last commit I am afraid), I installed it in `rocketchat.maindomain.tld` with the path `/`, which resulted in an error 404 when opening `https://rocketchat.maindomain.tld`.
In the `rocketchat.service` files, `ROOT_URL` was indeed defined as `ROOT_URL=https://rocketchat.maindomain.tld/:3000`. Where I could find my server! But this url was not very practical so I needed to change it.
After changing it to  `ROOT_URL=https://rocketchat.maindomain.tld/`, I was still not able to open rocket chat at this address.
Then I found this page explaining that `ROOT_URL` becomes stored in mongodb at the first connection, so you have to change it there also:
https://www.ryadel.com/en/rocket-chat-change-root_url-site-url-rocketchat/

The steps to change url:
```shell
> mongo
> use rocketchat
> db.rocketchat_settings.update({"_id" : "Site_Url"},{$set:{value:"<YOUR NEW URL>"}})
```

I thought it would be useful to implement the `change_url` script.

**Comment by ericgaspar** [comment]
Thanks for the feedback. RocketChat should be working now.

**Comment by getzze** [comment]
The update to version 4.1.2 worked well, thanks!
But the `change_url` script is not working.
`ROOT_URL` is not changed in `rocketchat.service` and more importantly "Site_Url" is not changed in mongodb, as I described in my first message.
Maybe adding the following to the `change_url` script could work:
```bash
db_name=$(ynh_sanitize_dbid --db_name=$app)
new_url="https://${new_domain}${new_path}"
ynh_mongo_exec --database="$db_name" --command='db.rocketchat_settings.update({"_id" : "Site_Url"}, {$set: {value: "'${new_url}'"}});'
```
