### ISSUE TITLE
MongoError: no primary found in replicaset or invalid replica set name

### ISSUE THREAD

**Issue by Ibrahim-AbouElseoud** [YunoHost-Apps/rocketchat_ynh#81]
Currently after installation, when rocket chat service tries to run it throws the following exception:
> MongoError: no primary found in replicaset or invalid replica set name rocketchat[20276]: at /var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:624:11

I found that a solution to this is to do the following that is mentioned here:
https://docs.rocket.chat/installing-and-updating/manual-installation/mongo-replicas

Which is to do:
1. `$ nano /etc/mongod.conf`

2. Add double quotes so it becomes  "rs01"

3. ctrl+o then enter then ctrl+x (to save changes)

 4. then follow the instructions in the link for the linked section and that's it.
 https://docs.rocket.chat/installing-and-updating/manual-installation/mongo-replicas#restart-mongodb-and-initiate-the-replica-set

**Comment by Ibrahim-AbouElseoud** [comment]
Maybe it gets fixed in a future update, but this was what worked with me to make rocket chat work if you get this error after installation so thought I'd share in case others were in the same predicament.

**Comment by ericgaspar** [comment]
Thanks for testing! we should have a working version now.
