### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by DizzySasquatch** [YunoHost-Apps/rocketchat_ynh#98]
Hello,

thanks for creating this package. Unfortunately I can't get it running.

### Describe the bug

I tried to install RocketChat through the Yunohost Web-UI or via the console. The installation failed.

Notable error messages:

`'/etc/apt/trusted.gpg.d/rocketchat.asc' wasn't deleted because it doesn't exist.`

`The service mongod didn't fully executed the action restart before the timeout.`

`systemd[1]: mongod.service: Main process exited, code=killed, status=4/ILL`
`systemd[1]: mongod.service: Failed with result 'signal'.`

`_common.sh: line 45:  6894 Illegal instruction     mongo --quiet $user $password $authenticationdatabase $host $port <<EOF`

I tried with and without a path while installing on a subdomain or with the default path (`/rocketchat`) while installing on the main domain. All resulted in the same error messages.

### Context

- Hardware: Windows 10 PC with Yunohost running in a VM
- YunoHost version: 4.3.5
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen - all of them
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - Tried to install other apps on diiferent subdomains or the main domain, which worked without any issues
- Using, or trying to install package version/branch: 4.3.0~ynh1 (from the Web-UI)

### Steps to reproduce

- *If you used the webadmin, please perform the equivalent command from the CLI first.*
  - also tried `sudo yunohost app install rocketchat`
  - same result
- *If the error occurs in your browser, explain what you did:*
   1. Go to 'Applicaitons'
   2. Search for "RocketChat"
   3. Click on "Install"
   4. Settings:
     - Label: RocketChat
     - Domain: *subdomain.mydomain.tld*
     - URL-Path: /
     - Administrator: *my account*
     - Anonymous visitors: yes
     - Administration Password: *a randomly generated secure password*
   5. Click on "Install"
   6. After waiting for installation process to finish read logs

### Expected behavior

RocketChat installs successfully

**Comment by ericgaspar** [comment]
Can you try to install from this branch?
```
sudo yunohost app install https://github.com/YunoHost-Apps/rocketchat_ynh/tree/remove-mongo_exec
```

**Comment by DizzySasquatch** [comment]
Just tried this, but still fails to install with the same error messages.

**Comment by ericgaspar** [comment]
Can you please share the full logs?

**Comment by DizzySasquatch** [comment]
That's the one from `sudo yunohost app install https://github.com/YunoHost-Apps/rocketchat_ynh/tree/remove-mongo_exec`

https://paste.yunohost.org/raw/agifiyurik

**Comment by cgman7** [comment]
Ohh.. you can see my log too!
https://paste.yunohost.org/raw/dasenabowu

**Comment by sthaydn** [comment]
I have the same issue, with Yunohost 11.0.6+202204201945. The install method `sudo yunohost app install https://github.com/YunoHost-Apps/rocketchat_ynh/tree/remove-mongo_exec` doesn't seem to exist anymore. In services the mongoDB is still there with error.

**Comment by sthaydn** [comment]
When trying to install testing, the error is the same.

**Comment by ericgaspar** [comment]
@sthaydn I can't figure out why NodeJS 12 is being installed instead of  NodeJS 14 as set in the install script...

**Comment by DizzySasquatch** [comment]
@sthaydn do you have Yunohost running in a virtual machine, or on a dedicated or v-server? For me it didn't work in a VM, but works just fine on a remote v-server.

@ericgaspar is it possible that this might be the issue here?

**Comment by sthaydn** [comment]
No, it is a VPS on netcup, sorry.

**Comment by sthaydn** [comment]
> @sthaydn I can't figure out why NodeJS 12 is being installed instead of NodeJS 14 as set in the install script...

I do not have knowledge about this at all and maybe it sounds stupid, but does it make a difference putting the version number into quotation marks?

Another idea: I also have Rocket.Chat installed on a VM at home, there is the exact version needed to get it working, when I recall it right. Maybe putting 14.18.3 (for RocketChat 4.6.3) as nodejs_version could help?

**Comment by stemy2** [comment]
Same

https://paste.yunohost.org/raw/xorofafari
